### PR TITLE
allow comments and dollar signs in strings

### PR DESCRIPTION
**Pull request by brandonspark**
This PR fixes the Kotlin parser so that comments are allowed in strings.

It's mostly derived from the equivalent code for the Julia tree-sitter parser.

Test plan: Automated tests.

I also used a script to test out the parser on a bunch of Kotlin repos, and went from 97% parse success to 98.344%.

### CODE REVIEW

**Comment by brandonspark** [comment]
@fwcd

**Comment by fwcd** [comment]
Thanks, could you rebase this onto main and regenerate the parser?

**Comment by brandonspark** [comment]
@fwcd Done!

**Comment by fwcd** [comment]
If the CI-generated parser doesn't match up with your local version, try updating the npm dependencies, the new `tree-sitter-cli` recently changed some parts of this (you can see the diff in the CI workflow).

**Pull request merged**
