### PR TITLE
add a conflict for postfix suffix

### PR DESCRIPTION
**Pull request by colleend**
Fixes the issue of the this assignment fix lowering our parsing rate; currently getting an `86.230%` parsing rate, up from the 83.5% we have without this fix 😄 

cc: @aryx

### CODE REVIEW

**Comment by aryx** [comment]
cc @fwcd any chance we can get this merge soon?

**Comment by aryx** [comment]
BTW @fwcd do you prefer that (1) we make PR just modifying the grammar.js or (2) we should also regenerate the parser.c and other files and make that part of the PR? I prefer (1), because that's the only thing we really care about, and on our side we regenerate each time anway with our own version of tree-sitter-cli, so we don't care about those generated parser.c in the tree-sitter-kotlin repo, but if (2) is more convenient for you we can do it too.

**Comment by fwcd** [comment]
Sure, lgtm. I would be fine with updates to the grammar for now, we could regenerate the parser once needed (e.g. before the next release) or perhaps let a GitHub action do this automatically.

**Comment by aryx** [comment]
perfect!

**Pull request merged**
