### PR TITLE
Expose null_literal as a node

### PR DESCRIPTION
**Pull request by afroozeh**
We need to expose null literals in parse trees, otherwise, it will not be possible to syntactically differentiate between some constructs. Example: currently, these two functions yield the same parse tree:
```
fun f() = null
fun f() { }
```
```
source_file
  function_declaration
    simple_identifier
    function_value_parameters
    function_body
```

With the changes in this PR, the first function will have a `null_literal` in the tree:
```
source_file
  function_declaration
    simple_identifier
    function_value_parameters
    function_body
      null_literal
```

Fixes https://github.com/fwcd/tree-sitter-kotlin/issues/140

### CODE REVIEW

**Comment by wolfmanstout** [comment]
> @fwcd Can you please check this PR? I have some other PRs that are stacked and like to merge them. I really don't want to fork the work on `tree-sitter-kotlin`, but expect some faster response time from you. 
> 
> Also, it seems like someone posted an exact duplicate of this PR: https://github.com/fwcd/tree-sitter-kotlin/pull/141
> 
> It doesn't matter for me which one gets merged, but let's merge one of them and move on with this one.

+1 I just closed my dupe PR. I hadn't seen this one when I made that but it's very similar.

**Comment by wolfmanstout** [comment]
> @wolfmanstout please check the new commit. It adds the changes from your PR to this one.

Looks great, thanks.

**Comment by wolfmanstout** [comment]
> @wolfmanstout please check the new commit. It adds the changes from your PR to this one.

Please also update the PR description to include "Fixes #140".

**Comment by fwcd** [comment]
Thanks!

**Pull request merged**
