### PR TITLE
Supporting functional interfaces

### LINKED ISSUE #87: Functional interface parsing has ERROR
There is an error parsing functional interfaces.

For example (from kotlinlang.org):

```kotlin
fun interface IntPredicate {
   fun accept(i: Int): Boolean
}
```

The node which should represent the body/`accept` method is an error, rather than correctly parsing out the abstract function.

### PR DESCRIPTION
**Pull request by bricka**
https://kotlinlang.org/docs/fun-interfaces.html

Closes #87

### CODE REVIEW

**Comment by VladimirMakaev** [comment]
@bricka Can you please rebase your fix and regenerate the parser?

**Comment by bricka** [comment]
@VladimirMakaev Rebased and regenerated :)

**Comment by bricka** [comment]
Hrm...I just tried redoing the `tree-sitter generate`, but my local one shows no changes to `parser.c`. Any ideas what could be causing the failed check?

**Comment by VladimirMakaev** [comment]
Can it be due to this https://github.com/fwcd/tree-sitter-kotlin/issues/92?

**Comment by bricka** [comment]
I tried to re-generate inside the `node:18` image, but that didn't seem to fix the problem for me :(

**Comment by bricka** [comment]
I think my last attempt was on my Mac laptop, but I've just made a change from my Linux laptop. Let's see if that makes the parser generation work correctly.

**Comment by VladimirMakaev** [comment]
I'm going to revert this for now since it broke the build

**Comment by bricka** [comment]
@VladimirMakaev Hi Vladimir. Did it break because of the generated parser?

If so, how can we push this forward? Could someone who can generate the parser correctly check out this branch, generate the parser, and then push that?

**Pull request merged**
